### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by meteorshowers** [feihuzhang/DSMNet#2]

**Comment by meteorshowers** [comment]
I train the psmnet on sceneflow and test it on the kitti2015dataset,
the 1--5pixel error is 
50 39 30 24 20  %
it is far from 17% error which is reported in your paper.
Could you please explain the reason?
I emailed you before.
Thanks.

**Comment by mli0603** [comment]
@meteorshowers Did you figure out what was the issue?
